import { supabase } from './supabase';
import { LOCALES } from '../locales';

// Per-child voice clips generated by /api/generate-name-audio (same voices
// as the stock praise clips). Clips are cached PER LANGUAGE: the profile's
// name_audio_paths jsonb maps locale → path, so switching back to a
// language the child already has clips for is free; name_audio_path is the
// legacy single-slot pointer that pre-migration rows (and stale
// localStorage profile caches) still carry. A path ending in manifest.json
// = personalized praise clips exist alongside a neutral name clip; a bare
// audio path is the neutral-only format (the self-heal in
// ChildProfileContext regenerates those). Paths are timestamped per
// version, so a rename is a brand-new URL — caches bust for free, and
// Cache Storage makes repeat plays instant/offline-safe.

const BUCKET = 'name-audio';
const CACHE_NAME = 'name-audio-v1';

// The locale a child's clips are (or would be) generated in — the API
// applies the same unknown-language → en fallback.
export const clipLocale = (profile) =>
  LOCALES[profile?.settings?.language] ? profile.settings.language : 'en';

// Per-locale lookup, falling back to the legacy single slot for rows the
// migration (or a fresh fetch) hasn't reached; wrong-language legacy clips
// are filtered at playback by the manifest's own locale field.
export const resolveNameAudioPath = (profile, locale) =>
  profile?.name_audio_paths?.[locale] ?? profile?.name_audio_path ?? null;

export const nameAudioUrl = (path) =>
  path ? supabase.storage.from(BUCKET).getPublicUrl(path).data.publicUrl : null;

export const isPraiseManifest = (path) =>
  typeof path === 'string' && path.endsWith('/manifest.json');

// The neutral name clip for a profile in either path format.
export const neutralNameUrl = (path) =>
  isPraiseManifest(path)
    ? nameAudioUrl(path.replace(/manifest\.json$/, 'name.mp3'))
    : nameAudioUrl(path);

// Cache-first fetch. URLs are versioned (timestamped folders), so a cache
// hit is always current. Cache Storage may be unavailable (private mode,
// insecure context) — then it's just a plain fetch.
const fetchCached = async (url) => {
  let cache = null;
  try {
    cache = await caches.open(CACHE_NAME);
    const hit = await cache.match(url);
    if (hit) return hit;
  } catch {
    /* no Cache Storage — network only */
  }
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  if (cache) {
    try {
      await cache.put(url, res.clone());
    } catch {
      /* quota — cache is best-effort */
    }
  }
  return res;
};

// Old versions become unreachable on regeneration; drop their cache
// entries so storage doesn't grow with every rename. Only sibling
// <timestamp> folders in the manifest's own scope (uid/cid/locale, or
// uid/cid for legacy pre-locale paths) are stale — other locales' cached
// clips live in differently-named folders and must survive.
const pruneStaleEntries = async (manifestPath) => {
  try {
    const scopePrefix = manifestPath.split('/').slice(0, -2).join('/');
    const versionRe = new RegExp(`/${scopePrefix}/\\d+/`);
    const folder = manifestPath.replace(/manifest\.json$/, '');
    const cache = await caches.open(CACHE_NAME);
    const keys = await cache.keys();
    await Promise.all(
      keys
        .filter((req) => versionRe.test(req.url) && !req.url.includes(`/${folder}`))
        .map((req) => cache.delete(req))
    );
  } catch {
    /* best-effort */
  }
};

// Loaded manifests, keyed by path: { name, tiers: { 0: [url, ...], ... } }.
// A failed load is evicted so the next call retries (e.g. back online).
const manifests = new Map();

export const loadPraiseClips = (path) => {
  if (!isPraiseManifest(path)) return Promise.resolve(null);
  if (!manifests.has(path)) {
    const load = async () => {
      const res = await fetchCached(nameAudioUrl(path));
      const manifest = await res.json();
      const folder = path.replace(/manifest\.json$/, '');
      const tiers = {};
      Object.entries(manifest.tiers || {}).forEach(([tier, files]) => {
        tiers[tier] = files.map((f) => nameAudioUrl(folder + f));
      });
      pruneStaleEntries(path);
      // locale was stamped from the child's language at generation time;
      // manifests older than the field are English with an mp3 neutral clip
      return {
        name: manifest.name,
        locale: manifest.locale ?? 'en',
        neutralUrl: nameAudioUrl(folder + (manifest.neutral || 'name.mp3')),
        tiers,
      };
    };
    manifests.set(
      path,
      load().catch(() => {
        manifests.delete(path);
        return null;
      })
    );
  }
  return manifests.get(path);
};

// Play one clip, cache-first; resolves when playback ends (or fails —
// praise must never stall a game).
export const playClipUrl = async (url) => {
  let src = url;
  try {
    const res = await fetchCached(url);
    src = URL.createObjectURL(await res.blob());
  } catch {
    /* stream straight from the network URL */
  }
  await new Promise((resolve) => {
    const audio = new Audio(src);
    audio.onended = resolve;
    audio.onerror = resolve;
    audio.play().catch(resolve);
  });
  if (src !== url) URL.revokeObjectURL(src);
};
