import { supabase } from './supabase';

// The child's neutral name clip (generated by /api/generate-name-audio,
// same ElevenLabs voice as the praise clips). Currently used only by the
// Parent Zone play button as confirmation the name was recorded; the
// personalized praise phrases that will replace it in games are planned in
// CUSTOM_PRAISE_PLAN.md. Paths are timestamped on regeneration, so a rename
// is a brand-new URL — caches bust for free.

const BUCKET = 'name-audio';

export const nameAudioUrl = (path) =>
  path ? supabase.storage.from(BUCKET).getPublicUrl(path).data.publicUrl : null;
